export const CATEGORIES = [
  {
    id: 1,
    value: "business",
    label: "Business",
  },
  {
    id: 2,
    value: "technology",
    label: "Technology",
  },
  {
    id: 3,
    value: "entertainment",
    label: "Entertainment",
  },
  {
    id: 4,
    value: "science",
    label: "Science",
  },
  {
    id: 5,
    value: "health",
    label: "Health",
  },
  {
    id: 6,
    value: "sports",
    label: "Sports",
  },
] as const;

export const KNOWIVATE_CATEGORIES = [
  {
    id: 1,
    value: "latest",
    label: "Latest",
  },
  {
    id: 2,
    value: "local",
    label: "Local",
  },
  {
    id: 3,
    value: "agriculture",
    label: "Agriculture",
  },
  {
    id: 4,
    value: "business",
    label: "Business",
  },
  {
    id: 5,
    value: "technologies",
    label: "Technology",
  },
  {
    id: 6,
    value: "sports",
    label: "Sports",
  },
] as const;

export const COUNTRIES = [
  { name: "Andorra", code: "ad" },
  { name: "United Arab Emirates", code: "ae" },
  { name: "Afghanistan", code: "af" },
  { name: "Anguilla", code: "ai" },
  { name: "Albania", code: "al" },
  { name: "Armenia", code: "am" },
  { name: "Angola", code: "ao" },
  { name: "Argentina", code: "ar" },
  { name: "Austria", code: "at" },
  { name: "Australia", code: "au" },
  { name: "Aruba", code: "aw" },
  { name: "Azerbaijan", code: "az" },
  { name: "Bosnia And Herzegovina", code: "ba" },
  { name: "Barbados", code: "bb" },
  { name: "Belgium", code: "be" },
  { name: "Burkina Faso", code: "bf" },
  { name: "Bulgaria", code: "bg" },
  { name: "Bahrain", code: "bh" },
  { name: "Burundi", code: "bi" },
  { name: "Benin", code: "bj" },
  { name: "Bermuda", code: "bm" },
  { name: "Brunei Darussalam", code: "bn" },
  { name: "Bolivia", code: "bo" },
  { name: "Brazil", code: "br" },
  { name: "Bahamas", code: "bs" },
  { name: "Botswana", code: "bw" },
  { name: "Belarus", code: "by" },
  { name: "Belize", code: "bz" },
  { name: "Canada", code: "ca" },
  { name: "Central African Republic", code: "cf" },
  { name: "Republic Of The Congo", code: "cg" },
  { name: "Switzerland", code: "ch" },
  { name: "Chile", code: "cl" },
  { name: "Cameroon", code: "cm" },
  { name: "China", code: "cn" },
  { name: "Colombia", code: "co" },
  { name: "Costa Rica", code: "cr" },
  { name: "Cuba", code: "cu" },
  { name: "Cape Verde", code: "cv" },
  { name: "Cyprus", code: "cy" },
  { name: "Czech Republic", code: "cz" },
  { name: "Germany", code: "de" },
  { name: "Djibouti", code: "dj" },
  { name: "Denmark", code: "dk" },
  { name: "Dominican Republic", code: "do" },
  { name: "Algeria", code: "dz" },
  { name: "Ecuador", code: "ec" },
  { name: "Estonia", code: "ee" },
  { name: "Egypt", code: "eg" },
  { name: "Eritrea", code: "er" },
  { name: "Spain", code: "es" },
  { name: "Ethiopia", code: "et" },
  { name: "Europe", code: "eu" },
  { name: "Finland", code: "fi" },
  { name: "Fiji", code: "fj" },
  { name: "Faroe Islands", code: "fo" },
  { name: "France", code: "fr" },
  { name: "Gabon", code: "ga" },
  { name: "United Kingdom", code: "gb" },
  { name: "Georgia", code: "ge" },
  { name: "French Guiana", code: "gf" },
  { name: "Guernsey", code: "gg" },
  { name: "Ghana", code: "gh" },
  { name: "Gambia", code: "gm" },
  { name: "Guinea", code: "gn" },
  { name: "Greece", code: "gr" },
  { name: "Guatemala", code: "gt" },
  { name: "Guinea-bissau", code: "gw" },
  { name: "Guyana", code: "gy" },
  { name: "Hong Kong", code: "hk" },
  { name: "Honduras", code: "hn" },
  { name: "Croatia", code: "hr" },
  { name: "Haiti", code: "ht" },
  { name: "Hungary", code: "hu" },
  { name: "Indonesia", code: "id" },
  { name: "Ireland", code: "ie" },
  { name: "Israel", code: "il" },
  { name: "Isle Of Man", code: "im" },
  { name: "India", code: "in" },
  { name: "British Indian Ocean Territory", code: "io" },
  { name: "Iraq", code: "iq" },
  { name: "Iran", code: "ir" },
  { name: "Iceland", code: "is" },
  { name: "Italy", code: "it" },
  { name: "Jamaica", code: "jm" },
  { name: "Jordan", code: "jo" },
  { name: "Japan", code: "jp" },
  { name: "Kenya", code: "ke" },
  { name: "Kyrgyzstan", code: "kg" },
  { name: "Cambodia", code: "kh" },
  { name: "North Korea", code: "kp" },
  { name: "South Korea", code: "kr" },
  { name: "Kuwait", code: "kw" },
  { name: "Cayman Islands", code: "ky" },
  { name: "Kazakhstan", code: "kz" },
  { name: "Laos", code: "la" },
  { name: "Lebanon", code: "lb" },
  { name: "Sri Lanka", code: "lk" },
  { name: "Liberia", code: "lr" },
  { name: "Lithuania", code: "lt" },
  { name: "Luxembourg", code: "lu" },
  { name: "Latvia", code: "lv" },
  { name: "Libya", code: "ly" },
  { name: "Morocco", code: "ma" },
  { name: "Monaco", code: "mc" },
  { name: "Moldova", code: "md" },
  { name: "Montenegro", code: "me" },
  { name: "Madagascar", code: "mg" },
  { name: "Macedonia", code: "mk" },
  { name: "Myanmar", code: "mm" },
  { name: "Mongolia", code: "mn" },
  { name: "Macao", code: "mo" },
  { name: "Northern Mariana Islands", code: "mp" },
  { name: "Mauritania", code: "mr" },
  { name: "Malta", code: "mt" },
  { name: "Malawi", code: "mw" },
  { name: "Mexico", code: "mx" },
  { name: "Malaysia", code: "my" },
  { name: "Mozambique", code: "mz" },
  { name: "Namibia", code: "na" },
  { name: "Niger", code: "ne" },
  { name: "Nigeria", code: "ng" },
  { name: "Nicaragua", code: "ni" },
  { name: "Netherlands", code: "nl" },
  { name: "Norway", code: "no" },
  { name: "Nepal", code: "np" },
  { name: "New Zealand", code: "nz" },
  { name: "Panama", code: "pa" },
  { name: "Peru", code: "pe" },
  { name: "French Polynesia", code: "pf" },
  { name: "Papua New Guinea", code: "pg" },
  { name: "Philippines", code: "ph" },
  { name: "Pakistan", code: "pk" },
  { name: "Poland", code: "pl" },
  { name: "Puerto Rico", code: "pr" },
  { name: "Palestinian Territory", code: "ps" },
  { name: "Portugal", code: "pt" },
  { name: "Paraguay", code: "py" },
  { name: "Qatar", code: "qa" },
  { name: "Reunion", code: "re" },
  { name: "Romania", code: "ro" },
  { name: "Serbia", code: "rs" },
  { name: "Russia", code: "ru" },
  { name: "Rwanda", code: "rw" },
  { name: "Saudi Arabia", code: "sa" },
  { name: "Solomon Islands", code: "sb" },
  { name: "Sudan", code: "sd" },
  { name: "Sweden", code: "se" },
  { name: "Singapore", code: "sg" },
  { name: "Slovenia", code: "si" },
  { name: "Slovakia", code: "sk" },
  { name: "Sierra Leone", code: "sl" },
  { name: "San Marino", code: "sm" },
  { name: "Senegal", code: "sn" },
  { name: "Somalia", code: "so" },
  { name: "Suriname", code: "sr" },
  { name: "South Sudan", code: "ss" },
  { name: "Sao Tome And Principe", code: "st" },
  { name: "El Salvador", code: "sv" },
  { name: "Syria", code: "sy" },
  { name: "Swaziland", code: "sz" },
  { name: "Chad", code: "td" },
  { name: "Togo", code: "tg" },
  { name: "Thailand", code: "th" },
  { name: "Tajikistan", code: "tj" },
  { name: "Timor-leste", code: "tl" },
  { name: "Turkmenistan", code: "tm" },
  { name: "Tunisia", code: "tn" },
  { name: "Turkey", code: "tr" },
  { name: "Trinidad And Tobago", code: "tt" },
  { name: "Tuvalu", code: "tv" },
  { name: "Taiwan", code: "tw" },
  { name: "Tanzania", code: "tz" },
  { name: "Ukraine", code: "ua" },
  { name: "Uganda", code: "ug" },
  { name: "United States Of America", code: "us" },
  { name: "Uruguay", code: "uy" },
  { name: "Uzbekistan", code: "uz" },
  { name: "Holy See", code: "va" },
  { name: "Saint Vincent And The Grenadines", code: "vc" },
  { name: "Venezuela", code: "ve" },
  { name: "Virgin Islands, U.s.", code: "vi" },
  { name: "Vietnam", code: "vn" },
  { name: "Vanuatu", code: "vu" },
  { name: "Kosovo", code: "xk" },
  { name: "Yemen", code: "ye" },
  { name: "Mayotte", code: "yt" },
  { name: "South Africa", code: "za" },
  { name: "Zambia", code: "zm" },
  { name: "Zimbabwe", code: "zw" },
] as const;

export const EXPLORE_APP_CATEGORIES = [
  {
    id: 1,
    value: "/",
    label: "Home",
  },
  {
    id: 2,
    value: "/bookmarked",
    label: "Bookmarked News",
  },
  {
    id: 3,
    value: "/search",
    label: "Search News",
  },
  {
    id: 4,
    value: "/front-page",
    label: "Front Page News",
  },
] as const;
